### PR TITLE
Fix Spaces Flakiness

### LINKED ISSUE #4121: Spaces Very Flakey Overall
My general usage of spaces on mobile has not been great recently. 

Few issues I've found:
- [x] Re-ordering items doesn't save the first time, takes multiple tries to get it to save
- [x] Deleting an item from Space doesn't always work. Or it does, but it doesn't reflect that in the app (the item is still visible).
- [ ] Comments experience is poor #3942 
- [ ] Adding or changing an item doesn't save (if you close the space and re-open it still shows the original item)

Many of these issues have a common problem: the local version isn't working nicely with the GraphQL updates. Don't think this is a release blocker but should be fixed sometime soon.

cc @yozuysal @buracules @jonathangarelick @darinwf

### PR DESCRIPTION
**Pull request by buracules**
Fixed flakiness on space details screen.

The main problem was when we create a space item we are giving random id to the item. To fix that now i am calling refresh function when we add a new item.

### How was this tested?
- [x] I tested this manually
- [ ] I added automated tests
- [ ] Existing automated tests are enough to cover my changes

### Screenshots and screen recordings
Images or videos showing the effect of your PR.  Examples include:

#### Before
https://user-images.githubusercontent.com/15333612/182493051-78f35c9c-28ab-4011-8c5b-ca516bf7c1c4.mp4 

#### After
https://user-images.githubusercontent.com/15333612/182493172-30fc74ed-70f9-4f88-9b29-e8305c26ed2e.mp4

## Issues addressed
* Fixes #4121

### CODE REVIEW

**Comment by yozuysal** [comment]
when you say "when we create a space item", does that include regular clicks to the bookmark button or only to create a new item by giving url, title, description in the UI?

**Comment by yozuysal** [comment]
(I think the cases we heard does cover just regular uses of the  bookmark button as well. So trying to make sure)

**Comment by buracules** [comment]
> when you say "when we create a space item", does that include regular clicks to the bookmark button or only to create a new item by giving url, title, description in the UI?

Hmm i dont think so. Right now its only to create new item from spaces ui. Let me check the other one as well.

**Comment by yozuysal** [comment]
My interpretation was @evancrow was also running into this while just using the bookmark button as well. is that correct @evancrow ? Or were you using the + button from the detail UI?

**Comment by yozuysal** [comment]
Actually @evancrow another question, were you getting a "an error occurred" toast when you add items or was it failing in some different way?

**Comment by evancrow** [comment]
No error Toast. Sorry for the confusion on this, I sent some clarification to @buracules earlier in the form of a screen recording which I'll attach here too. All of the issues I had were from the DetailView ui. 

One example:
https://user-images.githubusercontent.com/37356984/182496191-41022342-d083-49d8-bcbc-16abe0027b90.MOV

**Comment by buracules** [comment]
> No error Toast. Sorry for the confusion on this, I sent some clarification to @buracules earlier in the form of a screen recording which I'll attach here too. All of the issues I had were from the DetailView ui. All were just around things either showing up after being deleted, duplicates after restoring an item, or items showing in the wrong order.
> 
> One example: https://user-images.githubusercontent.com/37356984/182496191-41022342-d083-49d8-bcbc-16abe0027b90.MOV

Is this reordering issue also happening after you add an item?

**Comment by evancrow** [comment]
Yup!

**Comment by darinwf** [comment]
Can you add an automated test to ensure that this does not regress again?

**Comment by buracules** [comment]
Sure i will look into it tomorrow with broken tests. 

I was trying to find what cause this and i tested with v1.33.4 and that version also has this bugs. It was happening for months and we had no idea

**Comment by evancrow** [comment]
@buracules Can we also say that this PR fixes #3918?

**Comment by buracules** [comment]
@evancrow It must be. But i will double check after i am done with broken tests.

**Comment by buracules** [comment]
CC @jonathangarelick

File: Client/Frontend/Browser/CardGrid/Card/CardModels.swift [hunk 1]
```diff
@@ -642,13 +643,20 @@ class SpaceCardModel: CardModel {
         listenForShowingDetails()
     }
 
-    func add(spaceID: String, url: String, title: String, description: String? = nil) {
+    var asdCancellable: AnyCancellable?
```
[the remark this answers is not in the document]
Comment (buracules) [reply Client/Frontend/Browser/CardGrid/Card/CardModels.swift:646]: oh that was for test i tought i deleted this one

File: Client/Frontend/Browser/CardGrid/AddOrUpdateSpaceView.swift [hunk 2]
```diff
@@ -254,8 +254,13 @@ struct AddOrUpdateSpaceView: View {
...
                             spaceModel.add(
-                                spaceID: space.id.id, url: urlText,
-                                title: titleText, description: descriptionText)
+                                spaceID: space.id.id,
+                                url: urlText,
+                                title: titleText,
+                                description: descriptionText,
+                                onCompletion: {
+                                    SpaceStore.shared.refreshSpace(spaceID: space.id.id)
+                                })
```
[the remark this answers is not in the document]
Comment (buracules) [reply Client/Frontend/Browser/CardGrid/AddOrUpdateSpaceView.swift:263]: Yes that makes sense i tried different things with this setup but now i dont need completion i can just call refresh

File: Client/Frontend/Browser/CardGrid/AddOrUpdateSpaceView.swift [hunk 3]
```diff
@@ -254,8 +254,13 @@ struct AddOrUpdateSpaceView: View {
                             // modify target spaceCardDetail's Data and signal changes
                             space.contentData?.insert(data, at: 0)
                             spaceModel.add(
-                                spaceID: space.id.id, url: urlText,
-                                title: titleText, description: descriptionText)
+                                spaceID: space.id.id,
+                                url: urlText,
+                                title: titleText,
+                                description: descriptionText,
+                                onCompletion: {
```
Comment (EdwardJTL) [inline Client/Frontend/Browser/CardGrid/AddOrUpdateSpaceView.swift:261]: nit: use trailing closure

File: Client/Frontend/Browser/CardGrid/Card/CardModels.swift [hunk 4]
```diff
@@ -642,13 +643,19 @@ class SpaceCardModel: CardModel {
...
-    func add(spaceID: String, url: String, title: String, description: String? = nil) {
+    func add(
+        spaceID: String, url: String, title: String, description: String? = nil,
+        onCompletion: (() -> Void)? = nil
+    ) {
         DispatchQueue.main.async {
             let request = SpaceServiceProvider.shared.addToSpaceWithURL(
                 spaceID: spaceID, url: url, title: title, description: description)
+
             request?.$state.sink { state in
```
Comment (EdwardJTL) [inline Client/Frontend/Browser/CardGrid/Card/CardModels.swift:654]: all of these should capture `[weak self]` since you are storing it on `self` now

File: Client/Frontend/Browser/Spaces/SpaceDetailList.swift [hunk 5]
```diff
@@ -166,18 +166,27 @@ struct SpaceDetailList: View {
...
+        let entities = offsets.compactMap { index in
             primitive.allDetails[index]
         }
 
+        let entitiesToBeDeleted = offsets.compactMap { index in
+            primitive.allDetails[index].item
+        }
+
         primitive.allDetails.remove(atOffsets: offsets)
+        if let spaceID = primitive.item?.id.id, let space = SpaceStore.shared.get(for: spaceID) {
```
Comment (EdwardJTL) [inline Client/Frontend/Browser/Spaces/SpaceDetailList.swift:179]: nit: separate lines

File: Client/Frontend/Browser/Spaces/SpaceDetailList.swift [hunk 6]
```diff
@@ -166,18 +166,27 @@ struct SpaceDetailList: View {
...
+            space.contentData?.remove(atOffsets: offsets)
+        }
         spacesModel.delete(
             space: primitive.id, entities: entitiesToBeDeleted, from: tabModel.manager.scene
         ) {
-            for index in 0..<entitiesToBeDeleted.count {
-                primitive.allDetails.insert(entitiesToBeDeleted[index], at: 0)
+            for index in 0..<entities.count {
```
Comment (EdwardJTL) [inline Client/Frontend/Browser/Spaces/SpaceDetailList.swift:185]: is this the same as 
`primitive.allDetails = entities.reversed() + primitive.allDetails`?

File: Client/Frontend/Browser/CardGrid/Card/CardModels.swift [hunk 7]
```diff
@@ -642,13 +643,19 @@ class SpaceCardModel: CardModel {
         listenForShowingDetails()
     }
 
-    func add(spaceID: String, url: String, title: String, description: String? = nil) {
+    func add(
+        spaceID: String, url: String, title: String, description: String? = nil,
+        onCompletion: (() -> Void)? = nil
+    ) {
         DispatchQueue.main.async {
             let request = SpaceServiceProvider.shared.addToSpaceWithURL(
```
Comment (EdwardJTL) [inline Client/Frontend/Browser/CardGrid/Card/CardModels.swift:651]: should these requests be completion handlers instead? i don't see the point of using combine for them.

**Review by EdwardJTL — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/CardGrid/AddOrUpdateSpaceView.swift (hunk 3 above)
Comment (buracules) [reply Client/Frontend/Browser/CardGrid/AddOrUpdateSpaceView.swift:261]: Will remove this

File: Client/Frontend/Browser/CardGrid/Card/CardModels.swift [hunk 8]
```diff
@@ -642,13 +642,18 @@ class SpaceCardModel: CardModel {
...
                 spaceID: spaceID, url: url, title: title, description: description)
+
             request?.$state.sink { state in
-                self.spaceNeedsRefresh = spaceID
-            }.cancel()
+                if case .success = state {
+                    SpaceStore.shared.refreshSpace(spaceID: spaceID)
```
[the remark this answers is not in the document]
Comment (buracules) [reply Client/Frontend/Browser/CardGrid/Card/CardModels.swift:654]: Yes. Since we add a new item we dont know its ID and thats the biggest issue. When we reorder, delete we need that id for others we can make local changes

**Comment by buracules** [comment]
> Reordering and deleting works well so far, but when I add an item to a Space, the Space doesn't go to the top of the grid.
> 
>  Simulator.Screen.Recording.-.iPhone.13.-.2022-08-03.at.11.40.59.mp4

I think we have to update lastModifiedTs/timestamp

**Comment by buracules** [comment]
> Also editing a Space name is not updating for me. It does update on the web interface in real time though.
> 
>  Simulator.Screen.Recording.-.iPhone.13.-.2022-08-03.at.11.43.38.mp4 
> note: it does update when I go back to the main grid, then revisit the detail page.

I remember we were talking with @yozuysal about update issues. But i couldn't figure out the reason. But we can do the same thing and refresh for now? What do you think?

**Comment by buracules** [comment]
> > > Also editing a Space name is not updating for me. It does update on the web interface in real time though.
> > > Simulator.Screen.Recording.-.iPhone.13.-.2022-08-03.at.11.43.38.mp4
> > > note: it does update when I go back to the main grid, then revisit the detail page.
> > 
> > 
> > I remember we were talking with @yozuysal about update issues. But i couldn't figure out the reason. But we can do the same thing and refresh for now? What do you think?
> 
> Yes I think generally what we should do here is revert to the previous behavior when necessary in order to get things working again. Then we can file an issue to deal with optimizing it later.

It's not working I remember this one i had to give random ids to views in order to work. But that's another problem.

File: Client/Frontend/Browser/CardGrid/Card/CardModels.swift (hunk 7 above)
Comment (EdwardJTL) [reply Client/Frontend/Browser/CardGrid/Card/CardModels.swift:649]: yes, combine is good at setting up processing pipelines and/or processing data that comes in a sequence.

in this case, the syntax makes the intention of the code less clear. it is suggesting that `$state` could publish multiple values, and that we want to keep observing the publisher. That's why I am suggesting a completion handler approach here.

File: Client/Frontend/Browser/CardGrid/Card/CardModels.swift [hunk 9]
```diff
@@ -659,32 +664,38 @@ class SpaceCardModel: CardModel {
...
 
     func delete(
-        space spaceID: String, entities: [SpaceEntityThumbnail], from scene: UIScene,
+        space spaceID: String, entities: [SpaceEntityData], from scene: UIScene,
         undoDeletion: @escaping () -> Void
     ) {
         DispatchQueue.main.async {
             let request = SpaceServiceProvider.shared.deleteSpaceItems(
                 spaceID: spaceID, ids: entities.map { $0.id })
             request?.$state.sink { state in
```
Comment (EdwardJTL) [inline Client/Frontend/Browser/CardGrid/Card/CardModels.swift:694]: [weak self]

File: Client/Frontend/Browser/CardGrid/Card/CardModels.swift [hunk 10]
```diff
@@ -719,17 +732,21 @@ class SpaceCardModel: CardModel {
...
-                    self.spaceNeedsRefresh = space.id.id
-                    space.isPublic = false
-                    self.objectWillChange.send()
-                }.cancel()
+                    if case .success = state {
+                        self.spaceNeedsRefresh = space.id.id
+                        space.isPublic = false
+                        self.objectWillChange.send()
+                    }
+                }.store(in: &self.mutationSubscriptions)
```
Comment (EdwardJTL) [inline Client/Frontend/Browser/CardGrid/Card/CardModels.swift:749]: ditto

File: Client/Frontend/Browser/CardGrid/Card/CardModels.swift [hunk 11]
```diff
@@ -739,10 +756,12 @@ class SpaceCardModel: CardModel {
             let request = SpaceServiceProvider.shared.addSoloACLs(
                 spaceID: space.id.id, emails: emails, acl: acl, note: note)
             request?.$state.sink { state in
```
Comment (EdwardJTL) [inline Client/Frontend/Browser/CardGrid/Card/CardModels.swift:758]: ditto

**Review by EdwardJTL — COMMENTED** [review]
some more weak self missing

**Comment by evancrow** [comment]
My issues seem to be fixed, so LGTM. I do notice that it takes a second or two for the app to correct itself, is this because it has to call SpaceService to update?

**Comment by buracules** [comment]
> My issues seem to be fixed, so LGTM. I do notice that it takes a second or two for the app to correct itself, is this because it has to call SpaceService to update?

Probably yes. This was just a quick fix for next step we can use the id from response instead of refreshing the space.

File: Client/Frontend/Browser/CardGrid/Card/CardModels.swift (hunk 4 above)
Comment (EdwardJTL) [reply Client/Frontend/Browser/CardGrid/Card/CardModels.swift:652]: there is one more here in the final change?

**Comment by EdwardJTL** [comment]
> @EdwardJTL I think you need to approve, it says the PR is still blocked.

there is still one missed weak self :(

**Review by EdwardJTL — APPROVED** [review]
nvm all good
