### PR TITLE
Remove superfluous completion handler call

### LINKED ISSUE #3092: Crash @ [ cancelQueuedAlerts ]
```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	0x1810950fc __exceptionPreprocess + 220 (NSException.m:200)
1   libobjc.A.dylib               	0x1998e5d64 objc_exception_throw + 60 (objc-exception.mm:565)
2   CoreFoundation                	0x1810ec230 +[NSException raise:format:] + 112 (NSException.m:156)
3   WebKit                        	0x18fa1a968 WebKit::CompletionHandlerCallChecker::completionHandlerHasBeenCalled() const + 232 (CompletionHandlerCallChecker.mm:80)
4   WebKit                        	0x18fbffa6c WTF::BlockPtr<void ()> WTF::BlockPtr<void ()>::fromCallable<WebKit::UIDelegate::UIClient::runJavaScriptAlert(WebKit::WebPageProxy&, WTF::String const&, WebKit::WebFrameProxy*, WebKit::FrameInfoData... + 28 (UIDelegate.mm:319)
5   Client                        	0x100f88588 cancel + 4 (BrowserPrompts.swift:57)
6   Client                        	0x100f88588 protocol witness for JSAlertInfo.cancel() in conformance MessageAlert + 20 (<compiler-generated>:56)
7   Client                        	0x1010c0028 forEach + 64 (Tab.swift:577)
8   Client                        	0x1010c0028 cancelQueuedAlerts + 64 (Tab.swift:576)
9   Client                        	0x1010c0028 specialized BrowserViewController.tab(_:willDeleteWebView:) + 148 (BrowserViewController.swift:1351)
10  Client                        	0x1010b2350 tab + 12 (<compiler-generated>:0)
11  Client                        	0x1010b2350 @objc BrowserViewController.tab(_:willDeleteWebView:) + 68
12  Client                        	0x10108848c Tab.close() + 368 (<compiler-generated>:0)
13  Client                        	0x100f23450 TabManager.removeTab(_:flushToDisk:notify:) + 784 (TabManager+CloseTabs.swift:59)
14  Client                        	0x100f21fec TabManager.removeTab(_:showToast:updateSelectedTab:) + 412 (TabManager+CloseTabs.swift:14)
15  Client                        	0x100e5f924 closure #1 in TabManager.close(_:) + 32 (BrowserPrimitive.swift:127)
16  Client                        	0x100e5f5e0 thunk for @callee_guaranteed () -> (@error @owned Error) + 20 (<compiler-generated>:0)
17  Client                        	0x100fa3858 partial apply for thunk for @callee_guaranteed () -> (@error @owned Error) + 16 (<compiler-generated>:0)
18  Client                        	0x100fa3e50 thunk for @callee_guaranteed () -> (@error @owned Error)partial apply + 12
19  SwiftUI                       	0x188bcc5f8 closure #1 in withTransaction<A>(_:_:) + 92 (Transaction.swift:97)
20  SwiftUI                       	0x188c033b0 partial apply for closure #1 in withTransaction<A>(_:_:) + 24 (<compiler-generated>:0)
21  libswiftCore.dylib            	0x185bb6004 withExtendedLifetime<A, B>(_:_:) + 28 (LifetimeManager.swift:27)
22  SwiftUI                       	0x188bf579c withTransaction<A>(_:_:) + 72 (Transaction.swift:88)
23  SwiftUI                       	0x188be65bc withAnimation<A>(_:_:) + 196 (Transaction.swift:112)
24  Client                        	0x100f94978 close + 40 (BrowserPrimitive.swift:126)
25  Client                        	0x100f94978 TabCardDetails.onClose() + 772 (CardDetails.swift:209)
26  Client                        	0x101149774 0x100d44000 + 4216692
27  SwiftUI                       	0x1890aa324 partial apply for implicit closure #2 in implicit closure #1 in WrappedButtonStyle.makeBody(configuration:) + 28 (PrimitiveButtonStyle.swift:87)
28  SwiftUI                       	0x1895390ac closure #1 in PressableGestureCallbacks.dispatch(phase:state:) + 48 (PressableGestureCallbacks.swift:30)
29  SwiftUI                       	0x188bafcd8 thunk for @escaping @callee_guaranteed () -> () + 28 (<compiler-generated>:0)
30  SwiftUI                       	0x188ad65a8 thunk for @escaping @callee_guaranteed () -> (@out ()) + 28 (<compiler-generated>:0)
31  SwiftUI                       	0x188bafcd8 thunk for @escaping @callee_guaranteed () -> () + 28 (<compiler-generated>:0)
32  SwiftUI                       	0x188ab15ec static Update.end() + 600 (<compiler-generated>:0)
33  SwiftUI                       	0x188aace20 EventBindingManager.send(_:) + 212 (Update.swift:57)
34  SwiftUI                       	0x188ab8344 specialized EventBindingBridge.send(_:source:) + 2160 (EventBindingBridge.swift:64)
35  SwiftUI                       	0x188ab05d8 UIKitGestureRecognizer.send(touches:event:phase:) + 76 (<compiler-generated>:0)
36  SwiftUI                       	0x188ab3a80 @objc UIKitGestureRecognizer.touchesBegan(_:with:) + 168
37  UIKitCore                     	0x18366bbe8 -[UIGestureRecognizer _componentsEnded:withEvent:] + 240 (UIGestureRecognizer.m:978)
38  UIKitCore                     	0x1838d2d18 -[UITouchesEvent _sendEventToGestureRecognizer:] + 568 (UITouchesEvent.m:483)
39  UIKitCore                     	0x183711ad4 __47-[UIGestureEnvironment _updateForEvent:window:]_block_invoke + 84 (UIGestureEnvironment.m:1304)
40  UIKitCore                     	0x18363bc68 -[UIGestureEnvironment _updateForEvent:window:] + 492 (UIGestureEnvironment.m:1317)
41  UIKitCore                     	0x183648f2c -[UIWindow sendEvent:] + 4428 (UIWindow.m:3265)
42  UIKitCore                     	0x1837f8e34 -[UIApplication sendEvent:] + 828 (UIApplication.m:11877)
43  UIKitCore                     	0x18361c140 __dispatchPreprocessedEventFromEventQueue + 7904 (UIEventDispatcher.m:2290)
44  UIKitCore                     	0x183610f2c __processEventQueue + 6760 (UIEventDispatcher.m:2597)
45  UIKitCore                     	0x184457d54 updateCycleEntry + 176 (UIEventDispatcher.m:102)
46  UIKitCore                     	0x183c82b44 _UIUpdateSequenceRun + 84 (_UIUpdateSequence.mm:112)
47  UIKitCore                     	0x1842ff84c schedulerStepScheduledMainSection + 144 (_UIUpdateCycleScheduler.m:1174)
48  UIKitCore                     	0x1842fee3c runloopSourceCallback + 60 (_UIUpdateCycleScheduler.m:1262)
49  CoreFoundation                	0x1810b70d0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28 (CFRunLoop.c:1972)
50  CoreFoundation                	0x1810c7d90 __CFRunLoopDoSource0 + 208 (CFRunLoop.c:2016)
51  CoreFoundation                	0x181002098 __CFRunLoopDoSources0 + 268 (CFRunLoop.c:2053)
52  CoreFoundation                	0x1810078a4 __CFRunLoopRun + 820 (CFRunLoop.c:2951)
53  CoreFoundation                	0x18101b468 CFRunLoopRunSpecific + 600 (CFRunLoop.c:3268)
54  GraphicsServices              	0x19cbbf38c GSEventRunModal + 164 (GSEvent.c:2200)
55  UIKitCore                     	0x1839be5d0 -[UIApplication _run] + 1100 (UIApplication.m:3493)
56  UIKitCore                     	0x18373cf74 UIApplicationMain + 364 (UIApplication.m:5047)
57  Client                        	0x100d4ea38 main + 244 (main.swift:19)
58  dyld                          	0x1016a9aa4 start + 520 (dyldMain.cpp:879)
```

This looks like a regression related to the addition of `tab(_:willDeleteWebView:)`... @jonathangarelick @evancrow FYI

### PR DESCRIPTION
**Pull request by jonathangarelick**
Was not given a lot to go on from the crash report, but I determined that the completion handler was being called more than once, which was a problem. This was due to cancelQueuedAlerts being called twice -- once in `Tab.close()` and once in `tab(_:willDeleteWebView)` in the BVC.

This PR removes the call to `cancelQueuedAlerts` in `Tab.close()`. I also removed a comment that was added 7 months ago, I figure it probably is not relevant now.

@darinwf I don't have 100% confidence that this will solve the problem, based on my limited knowledge of WebKit and the limited information provided. If you have some extra time, would really appreciate a sanity check to see if what I am doing makes sense. Thanks!

### How was this tested?
- [x] I tested this manually
- [ ] I added automated tests
- [ ] Existing automated tests are enough to cover my changes

## Issues addressed
* Fixes #3092

### CODE REVIEW

File: Client/Frontend/Browser/Tabs/Tab.swift [hunk 1]
```diff
@@ -365,17 +365,9 @@ class Tab: NSObject, ObservableObject {
...
-        /// the web view, so I’m chalking it up to Swift being lazy.
-        // DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(10)) { [weak webView] in
-        //    if let webView = webView {
-        //        assertionFailure("web view with URL \(webView.url ?? "(nil)") \(webView) was not deallocated")
-        //    }
-        // }
-
-        // The code from here down properly cleans up tabs when they are removed (reference GitHub issue #3022)
+
+        // The code from here down properly cleans up tabs when they are removed (reference GitHub issue #3022, 3092)
```
Comment (darinwf) [inline Client/Frontend/Browser/Tabs/Tab.swift:370]: I guess one potential issue is that `Tab.alertQueue` would not be cleared if `Tab.webView` is nil. That probably couldn't happen, but hmm...

Another approach might be to make `cancelQueuedAlerts` support being called multiple times. A way to do that would be to remove a queued alert after calling `cancel()` on it. Could have a loop calling `dequeueJavascriptAlertPrompt()` until that returns nil, calling `cancel()` on each one.

Probably still sensible to avoid redundant calls to `cancelQueuedAlerts` too.

Comment (jonathangarelick) [reply Client/Frontend/Browser/Tabs/Tab.swift]: Makes sense. Now this PR removes a redundant call to `cancelQueuedAlerts` and allows it to be called multiple times per your suggestion. Thanks for the review.

**Review by darinwf — APPROVED** [review]
Great, thank you!
